import type { Problem } from './types';

export const PROBLEMS: Problem[] = [
  // ===== CAPTURE (4 problems) =====
  {
    id: 'capture-001',
    title: 'Corner Capture',
    category: 'capture',
    difficulty: 1,
    boardSize: 9,
    description: 'Capture the white stone in the corner.',
    hint: 'A stone in the corner only has two liberties.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 0, y: 0 }, color: 'white' },
      { point: { x: 1, y: 0 }, color: 'black' },
    ],
    solutionTree: [
      { move: { x: 0, y: 1 }, isCorrect: true, label: 'Captured!', responses: [] },
    ],
  },
  {
    id: 'capture-002',
    title: 'Edge Squeeze',
    category: 'capture',
    difficulty: 1,
    boardSize: 9,
    description: 'Capture the white group on the edge.',
    hint: 'Reduce the group to zero liberties.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 3, y: 0 }, color: 'white' },
      { point: { x: 4, y: 0 }, color: 'white' },
      { point: { x: 2, y: 0 }, color: 'black' },
      { point: { x: 5, y: 0 }, color: 'black' },
      { point: { x: 3, y: 1 }, color: 'black' },
    ],
    solutionTree: [
      { move: { x: 4, y: 1 }, isCorrect: true, label: 'Captured the group!', responses: [] },
    ],
  },
  {
    id: 'capture-003',
    title: 'Loose Ladder',
    category: 'capture',
    difficulty: 2,
    boardSize: 9,
    description: 'Chase and capture the white stone.',
    hint: 'Keep reducing liberties — push toward the edge.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 4, y: 4 }, color: 'white' },
      { point: { x: 4, y: 3 }, color: 'black' },
      { point: { x: 3, y: 4 }, color: 'black' },
    ],
    solutionTree: [
      {
        move: { x: 5, y: 4 }, isCorrect: true, label: 'Atari!',
        responses: [
          {
            move: { x: 4, y: 5 }, isCorrect: true, label: 'White runs',
            responses: [
              { move: { x: 5, y: 5 }, isCorrect: true, label: 'Double atari — captured!', responses: [] },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'capture-004',
    title: 'Snapback Capture',
    category: 'capture',
    difficulty: 3,
    boardSize: 9,
    description: 'Use a sacrifice to capture a larger group.',
    hint: 'Sometimes you need to give a stone to take more.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 2, y: 2 }, color: 'white' },
      { point: { x: 3, y: 2 }, color: 'white' },
      { point: { x: 2, y: 3 }, color: 'white' },
      { point: { x: 1, y: 2 }, color: 'black' },
      { point: { x: 1, y: 3 }, color: 'black' },
      { point: { x: 2, y: 4 }, color: 'black' },
      { point: { x: 3, y: 3 }, color: 'black' },
      { point: { x: 4, y: 2 }, color: 'black' },
    ],
    solutionTree: [
      {
        move: { x: 2, y: 1 }, isCorrect: true, label: 'Sacrifice!',
        responses: [
          {
            move: { x: 3, y: 1 }, isCorrect: true, label: 'White captures',
            responses: [
              { move: { x: 2, y: 2 }, isCorrect: true, label: 'Snapback! White group captured.', responses: [] },
            ],
          },
        ],
      },
    ],
  },

  // ===== LIFE AND DEATH (4 problems) =====
  {
    id: 'life-001',
    title: 'Make Two Eyes',
    category: 'life-and-death',
    difficulty: 2,
    boardSize: 9,
    description: 'Black must make two eyes to live.',
    hint: 'Divide your space into two separate eyes.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 0, y: 0 }, color: 'black' },
      { point: { x: 1, y: 0 }, color: 'black' },
      { point: { x: 2, y: 0 }, color: 'black' },
      { point: { x: 3, y: 0 }, color: 'black' },
      { point: { x: 0, y: 1 }, color: 'black' },
      { point: { x: 3, y: 1 }, color: 'black' },
      { point: { x: 0, y: 2 }, color: 'white' },
      { point: { x: 1, y: 2 }, color: 'white' },
      { point: { x: 2, y: 2 }, color: 'white' },
      { point: { x: 3, y: 2 }, color: 'white' },
      { point: { x: 4, y: 1 }, color: 'white' },
      { point: { x: 4, y: 0 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 2, y: 1 }, isCorrect: true, label: 'Two eyes! Black lives.', responses: [] },
      { move: { x: 1, y: 1 }, isCorrect: false, label: 'Only one big eye — black is dead.', responses: [] },
    ],
  },
  {
    id: 'life-002',
    title: 'Kill the Group',
    category: 'life-and-death',
    difficulty: 2,
    boardSize: 9,
    description: 'White to kill the black group.',
    hint: 'Prevent black from making two eyes.',
    playerColor: 'white',
    setupStones: [
      { point: { x: 0, y: 0 }, color: 'black' },
      { point: { x: 1, y: 0 }, color: 'black' },
      { point: { x: 2, y: 0 }, color: 'black' },
      { point: { x: 0, y: 1 }, color: 'black' },
      { point: { x: 2, y: 1 }, color: 'black' },
      { point: { x: 0, y: 2 }, color: 'white' },
      { point: { x: 1, y: 2 }, color: 'white' },
      { point: { x: 2, y: 2 }, color: 'white' },
      { point: { x: 3, y: 1 }, color: 'white' },
      { point: { x: 3, y: 0 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 1, y: 1 }, isCorrect: true, label: 'Dead — only one eye!', responses: [] },
      { move: { x: 0, y: 1 }, isCorrect: false, label: 'Black can still divide the space.', responses: [] },
    ],
  },
  {
    id: 'life-003',
    title: 'L-Group Life',
    category: 'life-and-death',
    difficulty: 3,
    boardSize: 9,
    description: 'Black to live with the L-shaped group in the corner.',
    hint: 'Find the vital point that creates two eyes.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 0, y: 0 }, color: 'black' },
      { point: { x: 1, y: 0 }, color: 'black' },
      { point: { x: 0, y: 1 }, color: 'black' },
      { point: { x: 0, y: 2 }, color: 'black' },
      { point: { x: 1, y: 2 }, color: 'black' },
      { point: { x: 2, y: 0 }, color: 'white' },
      { point: { x: 2, y: 1 }, color: 'white' },
      { point: { x: 2, y: 2 }, color: 'white' },
      { point: { x: 1, y: 3 }, color: 'white' },
      { point: { x: 0, y: 3 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 1, y: 1 }, isCorrect: true, label: 'Alive! Two eyes formed.', responses: [] },
      { move: { x: 0, y: 1 }, isCorrect: false, label: 'Wrong shape — still only one eye.', responses: [] },
    ],
  },
  {
    id: 'life-004',
    title: 'Bent Four in the Corner',
    category: 'life-and-death',
    difficulty: 4,
    boardSize: 9,
    description: 'White to kill — the bent-four shape is dead.',
    hint: 'Play the vital point to prevent two eyes.',
    playerColor: 'white',
    setupStones: [
      { point: { x: 0, y: 0 }, color: 'black' },
      { point: { x: 1, y: 0 }, color: 'black' },
      { point: { x: 0, y: 1 }, color: 'black' },
      { point: { x: 0, y: 2 }, color: 'black' },
      { point: { x: 1, y: 1 }, color: 'white' },
      { point: { x: 2, y: 0 }, color: 'white' },
      { point: { x: 2, y: 1 }, color: 'white' },
      { point: { x: 1, y: 2 }, color: 'white' },
      { point: { x: 0, y: 3 }, color: 'white' },
    ],
    solutionTree: [
      {
        move: { x: 1, y: 0 }, isCorrect: true, label: 'Throw-in!',
        responses: [
          {
            move: { x: 0, y: 0 }, isCorrect: true, label: 'Black captures',
            responses: [
              { move: { x: 1, y: 0 }, isCorrect: true, label: 'Ko — bent four is dead under Japanese rules!', responses: [] },
            ],
          },
        ],
      },
    ],
  },

  // ===== TESUJI (4 problems) =====
  {
    id: 'tesuji-001',
    title: 'The Throw-In',
    category: 'tesuji',
    difficulty: 2,
    boardSize: 9,
    description: 'Use a throw-in to reduce eye space.',
    hint: 'Sacrifice a stone inside the opponent\'s territory.',
    playerColor: 'white',
    setupStones: [
      { point: { x: 0, y: 0 }, color: 'black' },
      { point: { x: 1, y: 0 }, color: 'black' },
      { point: { x: 2, y: 0 }, color: 'black' },
      { point: { x: 3, y: 0 }, color: 'black' },
      { point: { x: 0, y: 1 }, color: 'black' },
      { point: { x: 3, y: 1 }, color: 'black' },
      { point: { x: 0, y: 2 }, color: 'white' },
      { point: { x: 1, y: 2 }, color: 'white' },
      { point: { x: 2, y: 2 }, color: 'white' },
      { point: { x: 3, y: 2 }, color: 'white' },
      { point: { x: 4, y: 1 }, color: 'white' },
      { point: { x: 4, y: 0 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 2, y: 1 }, isCorrect: true, label: 'Throw-in! Black cannot make two eyes.', responses: [] },
      { move: { x: 1, y: 1 }, isCorrect: false, label: 'Black captures and lives.', responses: [] },
    ],
  },
  {
    id: 'tesuji-002',
    title: 'The Placement',
    category: 'tesuji',
    difficulty: 3,
    boardSize: 9,
    description: 'Find the key placement to capture.',
    hint: 'Place a stone where it creates two threats.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 4, y: 0 }, color: 'white' },
      { point: { x: 5, y: 0 }, color: 'white' },
      { point: { x: 6, y: 0 }, color: 'white' },
      { point: { x: 3, y: 0 }, color: 'black' },
      { point: { x: 3, y: 1 }, color: 'black' },
      { point: { x: 4, y: 2 }, color: 'black' },
      { point: { x: 5, y: 2 }, color: 'black' },
      { point: { x: 6, y: 2 }, color: 'black' },
      { point: { x: 7, y: 1 }, color: 'black' },
      { point: { x: 7, y: 0 }, color: 'black' },
    ],
    solutionTree: [
      { move: { x: 5, y: 1 }, isCorrect: true, label: 'Double atari! White cannot save both.', responses: [] },
      { move: { x: 4, y: 1 }, isCorrect: false, label: 'White escapes at 5,1.', responses: [] },
      { move: { x: 6, y: 1 }, isCorrect: false, label: 'White connects at 5,1.', responses: [] },
    ],
  },
  {
    id: 'tesuji-003',
    title: 'Bamboo Joint',
    category: 'tesuji',
    difficulty: 2,
    boardSize: 9,
    description: 'Connect your stones with the bamboo joint.',
    hint: 'A diagonal connection that cannot be cut.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 3, y: 3 }, color: 'black' },
      { point: { x: 5, y: 3 }, color: 'black' },
      { point: { x: 4, y: 4 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 4, y: 2 }, isCorrect: true, label: 'Bamboo joint! Unbreakable connection.', responses: [] },
      { move: { x: 4, y: 3 }, isCorrect: false, label: 'This can be cut. Think diagonally.', responses: [] },
    ],
  },
  {
    id: 'tesuji-004',
    title: 'Under the Stones',
    category: 'tesuji',
    difficulty: 4,
    boardSize: 9,
    description: 'Sacrifice stones then recapture for a bigger gain.',
    hint: 'Fill your own liberties to set up a snapback.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 1, y: 0 }, color: 'white' },
      { point: { x: 2, y: 0 }, color: 'white' },
      { point: { x: 3, y: 0 }, color: 'white' },
      { point: { x: 0, y: 1 }, color: 'white' },
      { point: { x: 3, y: 1 }, color: 'black' },
      { point: { x: 0, y: 2 }, color: 'black' },
      { point: { x: 1, y: 2 }, color: 'black' },
      { point: { x: 2, y: 2 }, color: 'black' },
      { point: { x: 3, y: 2 }, color: 'black' },
    ],
    solutionTree: [
      {
        move: { x: 1, y: 1 }, isCorrect: true, label: 'Sacrifice!',
        responses: [
          {
            move: { x: 2, y: 1 }, isCorrect: true, label: 'White takes',
            responses: [
              { move: { x: 0, y: 0 }, isCorrect: true, label: 'Under the stones! Recapture everything.', responses: [] },
            ],
          },
        ],
      },
    ],
  },

  // ===== READING (4 problems) =====
  {
    id: 'reading-001',
    title: 'Simple Ladder',
    category: 'reading',
    difficulty: 2,
    boardSize: 9,
    description: 'Read out the ladder — does it work?',
    hint: 'Follow the atari sequence to the edge.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 4, y: 4 }, color: 'white' },
      { point: { x: 5, y: 4 }, color: 'black' },
      { point: { x: 4, y: 3 }, color: 'black' },
    ],
    solutionTree: [
      {
        move: { x: 3, y: 4 }, isCorrect: true, label: 'Atari!',
        responses: [
          {
            move: { x: 3, y: 5 }, isCorrect: true, label: 'White flees',
            responses: [
              { move: { x: 4, y: 5 }, isCorrect: true, label: 'Keep chasing — ladder works!', responses: [] },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'reading-002',
    title: 'Net vs Ladder',
    category: 'reading',
    difficulty: 3,
    boardSize: 9,
    description: 'The ladder doesn\'t work. Find the net instead.',
    hint: 'A net (geta) catches a stone without chasing it.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 4, y: 4 }, color: 'white' },
      { point: { x: 5, y: 4 }, color: 'black' },
      { point: { x: 4, y: 3 }, color: 'black' },
      { point: { x: 2, y: 6 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 3, y: 5 }, isCorrect: true, label: 'Net! White cannot escape.', responses: [] },
      { move: { x: 3, y: 4 }, isCorrect: false, label: 'The ladder is broken — white escapes at 2,6.', responses: [] },
    ],
  },
  {
    id: 'reading-003',
    title: 'Connect and Cut',
    category: 'reading',
    difficulty: 3,
    boardSize: 9,
    description: 'Find the move that both connects your stones and cuts white.',
    hint: 'One move can serve two purposes.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 3, y: 3 }, color: 'black' },
      { point: { x: 5, y: 3 }, color: 'black' },
      { point: { x: 4, y: 4 }, color: 'white' },
      { point: { x: 4, y: 2 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 4, y: 3 }, isCorrect: true, label: 'Connect and cut! White is split.', responses: [] },
      { move: { x: 3, y: 4 }, isCorrect: false, label: 'This doesn\'t cut white.', responses: [] },
    ],
  },
  {
    id: 'reading-004',
    title: 'Escape or Connect',
    category: 'reading',
    difficulty: 4,
    boardSize: 9,
    description: 'Black stone is in atari. Find the move that saves it AND threatens.',
    hint: 'Running can also create a double atari.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 4, y: 4 }, color: 'black' },
      { point: { x: 3, y: 4 }, color: 'white' },
      { point: { x: 4, y: 3 }, color: 'white' },
      { point: { x: 5, y: 4 }, color: 'white' },
      { point: { x: 6, y: 3 }, color: 'black' },
      { point: { x: 3, y: 5 }, color: 'black' },
    ],
    solutionTree: [
      { move: { x: 4, y: 5 }, isCorrect: true, label: 'Escape with double atari!', responses: [] },
      { move: { x: 4, y: 6 }, isCorrect: false, label: 'You escaped but no counter-threat.', responses: [] },
    ],
  },

  // ===== ENDGAME (4 problems) =====
  {
    id: 'endgame-001',
    title: 'Biggest Endgame Move',
    category: 'endgame',
    difficulty: 2,
    boardSize: 9,
    description: 'Find the largest endgame move on the board.',
    hint: 'Count how many points each move is worth.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 0, y: 4 }, color: 'black' },
      { point: { x: 1, y: 4 }, color: 'black' },
      { point: { x: 2, y: 4 }, color: 'black' },
      { point: { x: 3, y: 4 }, color: 'black' },
      { point: { x: 4, y: 4 }, color: 'black' },
      { point: { x: 5, y: 4 }, color: 'white' },
      { point: { x: 6, y: 4 }, color: 'white' },
      { point: { x: 7, y: 4 }, color: 'white' },
      { point: { x: 8, y: 4 }, color: 'white' },
      { point: { x: 4, y: 5 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 4, y: 5 }, isCorrect: true, label: 'Biggest move — worth 6 points!', responses: [] },
      { move: { x: 0, y: 5 }, isCorrect: false, label: 'Too small — only 1 point.', responses: [] },
    ],
  },
  {
    id: 'endgame-002',
    title: 'Sente Endgame',
    category: 'endgame',
    difficulty: 3,
    boardSize: 9,
    description: 'Play the sente (forcing) endgame move first.',
    hint: 'A sente move forces a response — play it before gote moves.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 0, y: 3 }, color: 'black' },
      { point: { x: 1, y: 3 }, color: 'black' },
      { point: { x: 2, y: 3 }, color: 'black' },
      { point: { x: 3, y: 3 }, color: 'white' },
      { point: { x: 3, y: 2 }, color: 'white' },
      { point: { x: 3, y: 1 }, color: 'white' },
      { point: { x: 3, y: 0 }, color: 'white' },
      { point: { x: 2, y: 0 }, color: 'black' },
    ],
    solutionTree: [
      {
        move: { x: 2, y: 2 }, isCorrect: true, label: 'Sente! White must respond.',
        responses: [
          {
            move: { x: 2, y: 1 }, isCorrect: true, label: 'White defends',
            responses: [
              { move: { x: 0, y: 0 }, isCorrect: true, label: 'Now take the gote point. Good endgame!', responses: [] },
            ],
          },
        ],
      },
      { move: { x: 0, y: 0 }, isCorrect: false, label: 'Gote first is bad — play the sente move!', responses: [] },
    ],
  },
  {
    id: 'endgame-003',
    title: 'Monkey Jump',
    category: 'endgame',
    difficulty: 3,
    boardSize: 9,
    description: 'Use the monkey jump to steal points on the edge.',
    hint: 'The monkey jump is a 1-2 slide along the first line.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 5, y: 0 }, color: 'white' },
      { point: { x: 5, y: 1 }, color: 'white' },
      { point: { x: 3, y: 1 }, color: 'black' },
      { point: { x: 3, y: 0 }, color: 'black' },
    ],
    solutionTree: [
      { move: { x: 5, y: 0 }, isCorrect: false, label: 'Too close — white blocks easily.', responses: [] },
      { move: { x: 4, y: 0 }, isCorrect: true, label: 'Monkey jump! Hard for white to block.', responses: [] },
    ],
  },
  {
    id: 'endgame-004',
    title: 'Double Sente',
    category: 'endgame',
    difficulty: 5,
    boardSize: 9,
    description: 'Find the rare double-sente endgame move.',
    hint: 'A double-sente point is sente for BOTH sides — always play it first.',
    playerColor: 'black',
    setupStones: [
      { point: { x: 4, y: 2 }, color: 'black' },
      { point: { x: 4, y: 3 }, color: 'black' },
      { point: { x: 3, y: 4 }, color: 'black' },
      { point: { x: 5, y: 2 }, color: 'white' },
      { point: { x: 5, y: 3 }, color: 'white' },
      { point: { x: 5, y: 4 }, color: 'white' },
      { point: { x: 4, y: 5 }, color: 'white' },
    ],
    solutionTree: [
      { move: { x: 4, y: 4 }, isCorrect: true, label: 'Double sente! Both sides needed this point.', responses: [] },
      { move: { x: 3, y: 3 }, isCorrect: false, label: 'Valuable, but 4,4 is double sente — play it first.', responses: [] },
    ],
  },
];
